baseURL = "https://aykuttasil.github.io/hugo-static-site-with-actions/"
#languageCode = "en-us"
#title = "My New Hugo Site"

#baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Aykut Asil's Softare Book"
  subtitle    = "Software"
  copyright   = "© 2018"

  cover       = "img/blog-cover.jpg"
  description = "Little Notes"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "faketryghost"
  fbName = "fakeghost"
  githubName = "eueung"
  linkedinName = "eueung"
  mediumName = ""

  logo = "hugo-logo.png"
  orgName = "AykutAsil"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "AykutAsil"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Go"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "Pages"
  url = "/post/"
  weight = 98

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95


